### ISSUE TITLE
Fix URI creation from path

### ISSUE THREAD

**Issue by aeschli** [cg-cnu/vscode-krita-plugin-generator#1]
In 1.26 we discovered that several extensions call the 'vscode.openFolder' command with invalid file URIs:
```
cg-cnu.vscode-krita-plugin-generator/out/krita.js
18,30: .executeCommand("vscode.openFolder", repoUri, newWindow)
```

When creating a URI from a file path, always use `vscode.URI.file(path)`, e.g `vscode.URI.file('c:\\test')`
Use `vscode.URI.parse(uriString)` when the input string is in the form `scheme://authority/path`

See https://github.com/Microsoft/vscode/issues/57267 for more information or for questions.

**Comment by cg-cnu** [comment]
Hey @aeschli Thanks for the notification. This [commit](https://github.com/cg-cnu/vscode-krita-plugin-generator/commit/9124127c56a87067f878485ee4ccb551a6b37aa4) should fix the issue. Let me know otherwise. Cheers!

**Comment by aeschli** [comment]
@cg-cnu Thanks!
